import { WorkflowProgressKey } from "./index"
import { normalizeWorkflowProjectionInput, workflowproject } from "./presentation"

export function externalexample() {
  const updates = [
    {
      title: "External adoption",
      progress: {
        version: "workflow-progress.v2",
        workflow: {
          status: "running",
          name: "external-adoption",
          label: "External adoption",
          summary: "External workflow using the shared contract",
          started_at: "2026-04-24T10:00:00.000Z",
        },
        phase: {
          status: "active",
          key: "plan",
          label: "Planning",
          summary: "Define the external rollout",
        },
        round: {
          status: "active",
          current: 1,
          max: 1,
          label: "Round 1/1",
        },
        machine: {
          id: "ext-1",
          key: "external-adoption",
          label: "External machine",
          root_step_id: "plan",
          active_step_id: "plan",
          active_run_id: "run-plan",
          started_at: "2026-04-24T10:00:00.000Z",
          updated_at: "2026-04-24T10:00:00.000Z",
        },
        step_definitions: [
          { id: "plan", kind: "task", label: "Plan rollout", next: ["ship"] },
          { id: "ship", kind: "task", label: "Ship contract", next: ["done"] },
          { id: "done", kind: "terminal", label: "Done" },
        ],
        step_runs: [
          {
            id: "run-plan",
            seq: 0,
            step_id: "plan",
            status: "active",
            label: "Plan rollout",
            summary: "Writing the migration notes",
            started_at: "2026-04-24T10:00:00.000Z",
            actor: {
              id: "agent-ext",
              name: "external-bot",
              role: "author",
              status: "running",
              summary: "Drafting v2 adoption",
              updated_at: "2026-04-24T10:00:00.000Z",
            },
          },
        ],
        transitions: [
          {
            id: "wf-0",
            seq: 0,
            timestamp: "2026-04-24T10:00:00.000Z",
            level: "workflow",
            target_id: "workflow",
            to_state: "running",
            source: { type: "workflow", id: "external-adoption" },
          },
          {
            id: "step-0",
            seq: 1,
            timestamp: "2026-04-24T10:00:00.000Z",
            level: "step",
            target_id: "plan",
            run_id: "run-plan",
            to_state: "active",
            reason: "Kick off migration guidance",
            source: {
              type: "agent",
              id: "agent-ext",
              name: "external-bot",
              step_id: "plan",
              run_id: "run-plan",
            },
          },
        ],
        participants: [
          {
            id: "agent-ext",
            name: "external-bot",
            role: "author",
            status: "running",
            summary: "Drafting v2 adoption",
            updated_at: "2026-04-24T10:00:00.000Z",
            round: 1,
            step_id: "plan",
            run_id: "run-plan",
          },
        ],
      },
    },
    {
      title: "External adoption",
      progress: {
        version: "workflow-progress.v2",
        workflow: {
          status: "running",
          name: "external-adoption",
          label: "External adoption",
          summary: "External workflow using the shared contract",
          started_at: "2026-04-24T10:00:00.000Z",
        },
        phase: {
          status: "active",
          key: "ship",
          label: "Shipping",
          summary: "Emit v2 state",
        },
        machine: {
          id: "ext-1",
          key: "external-adoption",
          label: "External machine",
          root_step_id: "plan",
          active_step_id: "ship",
          active_run_id: "run-ship",
          started_at: "2026-04-24T10:00:00.000Z",
          updated_at: "2026-04-24T10:01:00.000Z",
        },
        step_definitions: [
          { id: "plan", kind: "task", label: "Plan rollout", next: ["ship"] },
          { id: "ship", kind: "task", label: "Ship contract", next: ["done"] },
          { id: "done", kind: "terminal", label: "Done" },
        ],
        step_runs: [
          {
            id: "run-plan",
            seq: 0,
            step_id: "plan",
            status: "completed",
            label: "Plan rollout",
            summary: "Migration notes approved",
            started_at: "2026-04-24T10:00:00.000Z",
            ended_at: "2026-04-24T10:01:00.000Z",
            actor: {
              id: "agent-ext",
              name: "external-bot",
              role: "author",
              status: "completed",
              summary: "Planning complete",
              updated_at: "2026-04-24T10:01:00.000Z",
            },
          },
          {
            id: "run-ship",
            seq: 1,
            step_id: "ship",
            status: "active",
            label: "Ship contract",
            summary: "Sending v2 payloads through ctx.status()",
            started_at: "2026-04-24T10:01:00.000Z",
            actor: {
              id: "agent-ext",
              name: "external-bot",
              role: "author",
              status: "running",
              summary: "Emitting state-machine updates",
              updated_at: "2026-04-24T10:01:00.000Z",
            },
          },
        ],
        transitions: [
          {
            id: "wf-0",
            seq: 0,
            timestamp: "2026-04-24T10:00:00.000Z",
            level: "workflow",
            target_id: "workflow",
            to_state: "running",
            source: { type: "workflow", id: "external-adoption" },
          },
          {
            id: "step-0",
            seq: 1,
            timestamp: "2026-04-24T10:00:00.000Z",
            level: "step",
            target_id: "plan",
            run_id: "run-plan",
            to_state: "active",
            reason: "Kick off migration guidance",
            source: {
              type: "agent",
              id: "agent-ext",
              name: "external-bot",
              step_id: "plan",
              run_id: "run-plan",
            },
          },
          {
            id: "step-1",
            seq: 2,
            timestamp: "2026-04-24T10:01:00.000Z",
            level: "step",
            target_id: "plan",
            run_id: "run-plan",
            from_state: "active",
            to_state: "completed",
            reason: "Migration notes approved",
            source: {
              type: "agent",
              id: "agent-ext",
              name: "external-bot",
              step_id: "plan",
              run_id: "run-plan",
            },
          },
          {
            id: "step-2",
            seq: 3,
            timestamp: "2026-04-24T10:01:00.000Z",
            level: "step",
            target_id: "ship",
            run_id: "run-ship",
            to_state: "active",
            reason: "Start emitting contract updates",
            source: {
              type: "agent",
              id: "agent-ext",
              name: "external-bot",
              participant_id: "agent-ext",
              step_id: "ship",
              run_id: "run-ship",
            },
          },
        ],
        participants: [
          {
            id: "agent-ext",
            name: "external-bot",
            role: "author",
            status: "running",
            summary: "Emitting state-machine updates",
            updated_at: "2026-04-24T10:01:00.000Z",
            round: 1,
            step_id: "ship",
            run_id: "run-ship",
          },
        ],
      },
    },
    {
      title: "External adoption",
      progress: {
        version: "workflow-progress.v2",
        workflow: {
          status: "done",
          name: "external-adoption",
          label: "External adoption",
          summary: "External workflow using the shared contract",
          started_at: "2026-04-24T10:00:00.000Z",
          ended_at: "2026-04-24T10:02:00.000Z",
        },
        phase: {
          status: "completed",
          key: "done",
          label: "Done",
          summary: "Shared projection rendered successfully",
        },
        round: {
          status: "completed",
          current: 1,
          max: 1,
          label: "Round 1/1",
        },
        machine: {
          id: "ext-1",
          key: "external-adoption",
          label: "External machine",
          root_step_id: "plan",
          active_step_id: "done",
          started_at: "2026-04-24T10:00:00.000Z",
          updated_at: "2026-04-24T10:02:00.000Z",
        },
        step_definitions: [
          { id: "plan", kind: "task", label: "Plan rollout", next: ["ship"] },
          { id: "ship", kind: "task", label: "Ship contract", next: ["done"] },
          { id: "done", kind: "terminal", label: "Done" },
        ],
        step_runs: [
          {
            id: "run-plan",
            seq: 0,
            step_id: "plan",
            status: "completed",
            label: "Plan rollout",
            summary: "Migration notes approved",
            started_at: "2026-04-24T10:00:00.000Z",
            ended_at: "2026-04-24T10:01:00.000Z",
            actor: {
              id: "agent-ext",
              name: "external-bot",
              role: "author",
              status: "completed",
              summary: "Planning complete",
              updated_at: "2026-04-24T10:01:00.000Z",
            },
          },
          {
            id: "run-ship",
            seq: 1,
            step_id: "ship",
            status: "completed",
            label: "Ship contract",
            summary: "ctx.status() emitted the shared contract",
            started_at: "2026-04-24T10:01:00.000Z",
            ended_at: "2026-04-24T10:02:00.000Z",
            actor: {
              id: "agent-ext",
              name: "external-bot",
              role: "author",
              status: "completed",
              summary: "Shared projection rendered in the TUI",
              updated_at: "2026-04-24T10:02:00.000Z",
            },
          },
        ],
        transitions: [
          {
            id: "wf-0",
            seq: 0,
            timestamp: "2026-04-24T10:00:00.000Z",
            level: "workflow",
            target_id: "workflow",
            to_state: "running",
            source: { type: "workflow", id: "external-adoption" },
          },
          {
            id: "step-0",
            seq: 1,
            timestamp: "2026-04-24T10:00:00.000Z",
            level: "step",
            target_id: "plan",
            run_id: "run-plan",
            to_state: "active",
            reason: "Kick off migration guidance",
            source: {
              type: "agent",
              id: "agent-ext",
              name: "external-bot",
              step_id: "plan",
              run_id: "run-plan",
            },
          },
          {
            id: "step-1",
            seq: 2,
            timestamp: "2026-04-24T10:01:00.000Z",
            level: "step",
            target_id: "plan",
            run_id: "run-plan",
            from_state: "active",
            to_state: "completed",
            reason: "Migration notes approved",
            source: {
              type: "agent",
              id: "agent-ext",
              name: "external-bot",
              step_id: "plan",
              run_id: "run-plan",
            },
          },
          {
            id: "step-2",
            seq: 3,
            timestamp: "2026-04-24T10:01:00.000Z",
            level: "step",
            target_id: "ship",
            run_id: "run-ship",
            to_state: "active",
            reason: "Start emitting contract updates",
            source: {
              type: "agent",
              id: "agent-ext",
              name: "external-bot",
              step_id: "ship",
              run_id: "run-ship",
            },
          },
          {
            id: "step-3",
            seq: 4,
            timestamp: "2026-04-24T10:02:00.000Z",
            level: "step",
            target_id: "ship",
            run_id: "run-ship",
            from_state: "active",
            to_state: "completed",
            reason: "Shared renderer verified",
            source: {
              type: "agent",
              id: "agent-ext",
              name: "external-bot",
              step_id: "ship",
              run_id: "run-ship",
            },
          },
          {
            id: "wf-1",
            seq: 5,
            timestamp: "2026-04-24T10:02:00.000Z",
            level: "workflow",
            target_id: "workflow",
            from_state: "running",
            to_state: "done",
            reason: "External workflow completed",
            source: { type: "workflow", id: "external-adoption" },
          },
        ],
        participants: [
          {
            id: "agent-ext",
            name: "external-bot",
            role: "author",
            status: "completed",
            summary: "Shared projection rendered in the TUI",
            updated_at: "2026-04-24T10:02:00.000Z",
            round: 1,
            step_id: "ship",
            run_id: "run-ship",
          },
        ],
      },
    },
  ] as const

  const progress = updates[updates.length - 1]?.progress
  if (!progress) throw new Error("expected final v2 progress")
  const normalized = normalizeWorkflowProjectionInput(progress, { name: "external-adoption" })
  if (!normalized) throw new Error("expected normalized workflow progress")
  const projection = workflowproject({
    progress,
    name: "external-adoption",
    tool_status: "completed",
  })
  if (!projection) throw new Error("expected workflow projection")

  return {
    updates,
    metadata: {
      [WorkflowProgressKey]: progress,
    },
    progress,
    normalized,
    projection,
  }
}
